### PR TITLE
Added directory inside cache to make it shown more friendly in CLion

### PR DESCRIPTION
**Pull request by pgorgon-hem**
Refering to #266 I changed directory structure of cache. To make it compatible with old cache I added logic moving old structure to new one.

### CODE REVIEW

**Comment by TheLartians** [comment]
Hey @pgorgon-hem, thanks for the PR! I see how this would help organisation in IDEs such as CLion, but tbh I'm not a fan of moving directories around in the cache. Note that you can have multiple projects using different versions of CPM.camke, which would create re-downloads and introduce unexpected bugs into projects as well as the dependencies change location.

I don't use CLion, but maybe there is some other way to fix the directory naming there? 🤔

**Comment by pgorgon-hem** [comment]
I absolutelly agree that moving directories may brake older builds, so maybe I can generate hash in another way and put new sources there, it should help. CLion uses [cmake-file-api](https://cmake.org/cmake/help/git-stage/manual/cmake-file-api.7.html) to get information about project. There are directories entries in reply and I suppose it gets information only from there. So CMake is a source of that information, not CLion itself.
image

**Comment by TheLartians** [comment]
It's definitely a better approach, would result in duplicate dependency downloads, depending on the CPM version but that wouldn't be problematic imo. Perhaps in the initial phase we could make the new path opt-in by using a flag / env variable like `CPM_NAMED_CACHE_DIRECTORIES` or similar. 

@iboB any takes on this?

**Comment by pgorgon-hem** [comment]
Agree. So I added CPM_USE_NAMED_CACHE_DIRECTORIES.

**Comment by pgorgon-hem** [comment]
Hi, any progress?

**Comment by TheLartians** [comment]
Hey, for some reason it seems that Travis is not reporting and I'm unable to restart the job... Could you try pushing an empty commit to trigger it?

**Comment by pgorgon-hem** [comment]
I used oportunity and added description of that function to readme.

**Comment by pgorgon-hem** [comment]
I see that travis still can't report. Additionally I don't know why style doesn't work, do you have any idea?

**Comment by TheLartians** [comment]
@pgorgon-hem could you pull from master and try again? I've fixed the code creating styling problems and the checks should now all run on GitHub.

**Comment by pgorgon-hem** [comment]
> @pgorgon-hem could you pull from master and try again? I've fixed the code creating styling problems and the checks should now all run on GitHub.

I've merged master and now it works!

**Review by TheLartians — APPROVED** [review]
Hey, sorry for the inactivity, I lost track of the PRs. Looks good, I still wonder if this is the best approach to fixing the naming, but I don't see any issue with including the feature!

**Comment by TheLartians** [comment]
Released in `v0.34.0` 🎉

**Comment by pgorgon-hem** [comment]
> Hey, sorry for the inactivity, I lost track of the PRs. Looks good, I still wonder if this is the best approach to fixing the naming, but I don't see any issue with including the feature!

Thx so much!

**Pull request merged**
