### PR TITLE
Expand absolute path later in get_cpm.cmake

### PR DESCRIPTION
**Pull request by kisielk**
Supports expanding tildes in the environment.

### CODE REVIEW

**Comment by iboB** [comment]
To make things clear: you need this because you have a tilde in an env var?

**Comment by kisielk** [comment]
Yes for example in CLion I was setting the `CPM_SOURCE_CACHE` environment variable for a build with a tilde as my home directory and it was not expanded. It led to some cryptic errors. This would allow that usage and I don't think it has any other negative consequences.

**Comment by iboB** [comment]
I'd say that it was CLion's fault for not expanding the tilde. Generally having literal tildes in env vars is considered bad practice. 

This indeed doesn't seem like it could break stuff.

**Review by iboB — APPROVED** [review]

**Review by TheLartians — APPROVED** [review]
Agreed, this doesn't seem like it would cause any issues.

**Pull request merged**
